### PR TITLE
Add soil texture

### PR DESCRIPTION
**Pull request by dan-tang-ssd**
This PR is submitted to add soil texture in Project Data tab page.

There are 5 columns related to soil texture. Here is the business logic:

1. We will show "final_texture_type_usda" and "second_texture_type_usda" if any of them has value.

2. If both "final_texture_type_usda" and "second_texture_type_usda" are empty, We will show "final_texture_type_fao" and "second_texture_type_fao" if any of them has value.

3. If both "final_texture_type_fao" and "second_texture_type_fao" are empty, We will show "simple_texture".

4. If "simple_texture" is empty, we will show "NOT YET RATED"

This business logic is implemented:
1. In database view "samples_merged_anchor_hub_trials", for data extraction in wide format.
2. In Sample model class, added an attribute for showing "soil_texture" in Project Data tab page in front end.

### CODE REVIEW

**Comment by dan-tang-ssd** [comment]
I made below changes:

1. Database view "samples_merged_anchor_hub_trials", add new column "soil_texture". This is for data extraction in wide format.

2. Data extraction, add "soil_texture" for data extraction in split format.

3. Sample model, add new attribute "soil_texture". Add "soil_texture" in $appends so that it will be added to array and json.
This is for showing "soil_texture" in Project Data tab page in front end

4. Project Data Table vue component, add a new column to show "soil_texture"

I cannot further proceed because I cannot compile the Vue component...
I got error when I run "npm run dev".
Um... I upgraded to node v18 for vite. Is it compatible with Vue component we used in soils platform...?

image

image

**Comment by dan-tang-ssd** [comment]
Data extraction files:

Wide format:
[mp-legumes-all_sample_data-2023-07-14 13 37 18.xlsx](https://github.com/stats4sd/ccrp-soils/files/12050966/mp-legumes-all_sample_data-2023-07-14.13.37.18.xlsx)

Spilt format:
[mp-legumes-samples-2023-07-14 13 37 46.xlsx](https://github.com/stats4sd/ccrp-soils/files/12050969/mp-legumes-samples-2023-07-14.13.37.46.xlsx)

---

Screen shots:

Data extractions
image

Data extraction in wide format
image

Data extraction in split format
image

Added new attribute "soil_texture" to Sample model
image

image

**Comment by dan-tang-ssd** [comment]
SQL for checking "soil_texture" content in TablePlus:

```
SELECT id, simple_texture, final_texture_type_usda, second_texture_type_usda, final_texture_type_fao, second_texture_type_fao, 
IFNULL(
	IFNULL(
		IFNULL(
			CONCAT(final_texture_type_usda, ',', IFNULL(second_texture_type_usda, '')), 
			CONCAT(final_texture_type_fao, ',', IFNULL(second_texture_type_fao, ''))
		), 
	simple_texture), 
'NOT YET RATED') AS soil_texture
FROM samples;
```

**Review by dave-mills — APPROVED** [review]
This looks good to me. I'm not surprised that you had issues recompiling the javascript on this older platform! I think this is good to merge and review on the staging site.

**Comment by dan-tang-ssd** [comment]
Staging env deployment is completed.
Performed testing with positive result.

As there is no project using database view "samples_merged_anchor_hub_trials", testing cannot be performed for data extraction in wide format to verify column "soil_texture" is added.

Below items have been verified with positive result:
1. new column "soil_texture" added in split format
2. "soil_texture" is added to Sample model

**Pull request merged**
